In [24]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import numpy as np
import matplotlib.pyplot as plt

In [7]:
import NJODE.data_utils as data_utils 
import NJODE.train as train 

param_dict: {'epochs': [200], 'batch_size': [200], 'save_every': [5], 'learning_rate': [0.001], 'test_size': [0.2], 'seed': [398], 'hidden_size': [10], 'bias': [True], 'dropout_rate': [0.1], 'ode_nn': [((50, 'tanh'), (50, 'tanh'))], 'readout_nn': [((50, 'tanh'), (50, 'tanh'))], 'enc_nn': [((50, 'tanh'), (50, 'tanh'))], 'use_rnn': [False], 'func_appl_X': [[]], 'solver': ['euler'], 'weight': [0.5], 'weight_decay': [1.0], 'dataset': ['BlackScholes', 'Heston', 'OrnsteinUhlenbeck'], 'dataset_id': [None], 'plot': [True], 'evaluate': [True], 'paths_to_plot': [(0, 1, 2, 3, 4)]}
param_dict: {'epochs': [100], 'batch_size': [20], 'save_every': [10], 'learning_rate': [0.001], 'test_size': [0.2], 'training_size': [200, 400, 800, 1600, 3200, 6400, 12800], 'seed': [398], 'hidden_size': [10], 'bias': [True], 'dropout_rate': [0.1], 'ode_nn': [((10, 'tanh'), (10, 'tanh'))], 'readout_nn': [((10, 'tanh'), (10, 'tanh'))], 'enc_nn': [((10, 'tanh'), (10, 'tanh'))], 'use_rnn': [False], 'func_appl_X': [[]], 's

In [8]:
dataset_dic = {
    'mean': np.array([1.2, 1.0, 1.5]).tolist(),
    'volatility': np.array([[0.2, 0.1, 0.1], [0.1, 0.25, 0.1], [0.1,0.1, 0.3]]).tolist(),
    'speed': np.array([[0.3, 0.0, 0.0], [0.0, 0.3, 0.0],[0.0,0.0,0.3]]).tolist(),
    'nb_paths': 10000,
    'nb_steps': 100,
    'S0': np.array([1.0, 1.5 ,2.0]).tolist(),
    'maturity': 1.0,
    'dimension': 3,
    'obs_perc': 1.0,
    'scheme': 'euler',
    'return_vol': False,
    'v0': 1,
    'hurst': 0.75,
    'FBMmethod': 'daviesharte',
    'model_name': 'OrnsteinUhlenbeckWithCrossTerms',
    'dt': 0.01
}

In [9]:
datasetpath, dataset_id = data_utils.create_dataset("OrnsteinUhlenbeckWithCrossTerms",dataset_dic)

In [10]:
dataset_id

94

In [11]:
dataset_metadata = data_utils.load_metadata(stock_model_name="OrnsteinUhlenbeckWithCrossTerms",time_id=94)

In [12]:
dataset_metadata["dimension"]

3

In [13]:
train.train(dataset="OrnsteinUhlenbeckWithCrossTerms", dataset_id=94, data_dict=dataset_dic, use_cond_exp = False, input_coords=[0,1,2,3,4,5,6,7,8], output_coords=[0,1,2,3,4,5,6,7,8], which_loss="easy", input_sig=False, level=2 )

{'FBMmethod': 'daviesharte', 'S0': [1.0, 1.5, 2.0], 'dimension': 3, 'dt': 0.01, 'hurst': 0.75, 'maturity': 1.0, 'mean': [1.2, 1.0, 1.5], 'model_name': 'OrnsteinUhlenbeckWithCrossTerms', 'nb_paths': 10000, 'nb_steps': 100, 'obs_perc': 1.0, 'return_vol': False, 'scheme': 'euler', 'speed': [[0.3, 0.0, 0.0], [0.0, 0.3, 0.0], [0.0, 0.0, 0.3]], 'v0': 1, 'volatility': [[0.2, 0.1, 0.1], [0.1, 0.25, 0.1], [0.1, 0.1, 0.3]]}
using loss: easy
neuralODE use input scaling with tanh
use residual network: input_size=9, output_size=10
use residual network: input_size=10, output_size=9
model-id: None

using CPU
input_coords: [0, 1, 2, 3, 4, 5, 6, 7, 8]
output_coords: [0, 1, 2, 3, 4, 5, 6, 7, 8]
input_size: 9
output_size: 9
signature_coords: [0, 1, 2, 3, 4, 5, 6, 7, 8]
new model_id=87
model params:
{"batch_size": 100, "bias": true, "data_dict": {"FBMmethod": "daviesharte", "S0": [1.0, 1.5, 2.0], "dimension": 3, "dt": 0.01, "hurst": 0.75, "maturity": 1.0, "mean": [1.2, 1.0, 1.5], "model_name": "OrnsteinUh

80it [00:14,  5.39it/s]


evaluating ...
epoch 1, weight=0.50000, train-loss=0.59640, optimal-val-loss=nan, val-loss=0.07065, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:987: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)
C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.07065
save model ...
saved!
save new best model: last-best-loss: inf, new-best-loss: 0.07065, epoch: 1
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.21it/s]


evaluating ...
epoch 2, weight=0.50000, train-loss=0.21742, optimal-val-loss=nan, val-loss=0.05935, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.05935
save model ...
saved!
save new best model: last-best-loss: 0.07065, new-best-loss: 0.05935, epoch: 2
saved!
----------------------------------------------------------------------------------------------------


80it [00:17,  4.54it/s]


evaluating ...
epoch 3, weight=0.50000, train-loss=0.12772, optimal-val-loss=nan, val-loss=0.05540, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.05540
save model ...
saved!
save new best model: last-best-loss: 0.05935, new-best-loss: 0.05540, epoch: 3
saved!
----------------------------------------------------------------------------------------------------


80it [00:17,  4.57it/s]


evaluating ...
epoch 4, weight=0.50000, train-loss=0.09795, optimal-val-loss=nan, val-loss=0.05327, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.05327
save model ...
saved!
save new best model: last-best-loss: 0.05540, new-best-loss: 0.05327, epoch: 4
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.21it/s]


evaluating ...
epoch 5, weight=0.50000, train-loss=0.07837, optimal-val-loss=nan, val-loss=0.05199, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.05199
save model ...
saved!
save new best model: last-best-loss: 0.05327, new-best-loss: 0.05199, epoch: 5
saved!
----------------------------------------------------------------------------------------------------


80it [00:17,  4.51it/s]


evaluating ...
epoch 6, weight=0.50000, train-loss=0.07349, optimal-val-loss=nan, val-loss=0.05110, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.05110
save model ...
saved!
save new best model: last-best-loss: 0.05199, new-best-loss: 0.05110, epoch: 6
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.35it/s]


evaluating ...
epoch 7, weight=0.50000, train-loss=0.06799, optimal-val-loss=nan, val-loss=0.05048, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.05048
save model ...
saved!
save new best model: last-best-loss: 0.05110, new-best-loss: 0.05048, epoch: 7
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.40it/s]


evaluating ...
epoch 8, weight=0.50000, train-loss=0.06374, optimal-val-loss=nan, val-loss=0.05005, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.05005
save model ...
saved!
save new best model: last-best-loss: 0.05048, new-best-loss: 0.05005, epoch: 8
saved!
----------------------------------------------------------------------------------------------------


80it [00:17,  4.58it/s]


evaluating ...
epoch 9, weight=0.50000, train-loss=0.06503, optimal-val-loss=nan, val-loss=0.04969, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04969
save model ...
saved!
save new best model: last-best-loss: 0.05005, new-best-loss: 0.04969, epoch: 9
saved!
----------------------------------------------------------------------------------------------------


80it [00:17,  4.59it/s]


evaluating ...
epoch 10, weight=0.50000, train-loss=0.05896, optimal-val-loss=nan, val-loss=0.04946, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04946
save model ...
saved!
save new best model: last-best-loss: 0.04969, new-best-loss: 0.04946, epoch: 10
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.25it/s]


evaluating ...
epoch 11, weight=0.50000, train-loss=0.06335, optimal-val-loss=nan, val-loss=0.04948, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04948
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:17,  4.57it/s]


evaluating ...
epoch 12, weight=0.50000, train-loss=0.05820, optimal-val-loss=nan, val-loss=0.04924, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04924
save model ...
saved!
save new best model: last-best-loss: 0.04946, new-best-loss: 0.04924, epoch: 12


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


saved!
----------------------------------------------------------------------------------------------------


80it [00:17,  4.50it/s]


evaluating ...
epoch 13, weight=0.50000, train-loss=0.05817, optimal-val-loss=nan, val-loss=0.04901, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04901
save model ...
saved!
save new best model: last-best-loss: 0.04924, new-best-loss: 0.04901, epoch: 13
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.29it/s]


evaluating ...
epoch 14, weight=0.50000, train-loss=0.05854, optimal-val-loss=nan, val-loss=0.04890, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04890
save model ...
saved!
save new best model: last-best-loss: 0.04901, new-best-loss: 0.04890, epoch: 14
saved!
----------------------------------------------------------------------------------------------------


80it [00:17,  4.51it/s]


evaluating ...
epoch 15, weight=0.50000, train-loss=0.05820, optimal-val-loss=nan, val-loss=0.04886, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04886
save model ...
saved!
save new best model: last-best-loss: 0.04890, new-best-loss: 0.04886, epoch: 15
saved!
----------------------------------------------------------------------------------------------------


80it [00:17,  4.48it/s]


evaluating ...
epoch 16, weight=0.50000, train-loss=0.05668, optimal-val-loss=nan, val-loss=0.04876, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04876
save model ...
saved!
save new best model: last-best-loss: 0.04886, new-best-loss: 0.04876, epoch: 16
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.19it/s]


evaluating ...
epoch 17, weight=0.50000, train-loss=0.05549, optimal-val-loss=nan, val-loss=0.04871, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04871
save model ...
saved!
save new best model: last-best-loss: 0.04876, new-best-loss: 0.04871, epoch: 17
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.33it/s]


evaluating ...
epoch 18, weight=0.50000, train-loss=0.05630, optimal-val-loss=nan, val-loss=0.04871, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04871
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:17,  4.47it/s]


evaluating ...
epoch 19, weight=0.50000, train-loss=0.05608, optimal-val-loss=nan, val-loss=0.04858, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04858
save model ...
saved!
save new best model: last-best-loss: 0.04871, new-best-loss: 0.04858, epoch: 19
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.29it/s]


evaluating ...
epoch 20, weight=0.50000, train-loss=0.05333, optimal-val-loss=nan, val-loss=0.04862, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04862
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.40it/s]


evaluating ...
epoch 21, weight=0.50000, train-loss=0.05355, optimal-val-loss=nan, val-loss=0.04846, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04846
save model ...
saved!
save new best model: last-best-loss: 0.04858, new-best-loss: 0.04846, epoch: 21
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.22it/s]


evaluating ...
epoch 22, weight=0.50000, train-loss=0.05218, optimal-val-loss=nan, val-loss=0.04844, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04844
save model ...
saved!
save new best model: last-best-loss: 0.04846, new-best-loss: 0.04844, epoch: 22
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.20it/s]


evaluating ...
epoch 23, weight=0.50000, train-loss=0.05357, optimal-val-loss=nan, val-loss=0.04850, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04850
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.37it/s]


evaluating ...
epoch 24, weight=0.50000, train-loss=0.05283, optimal-val-loss=nan, val-loss=0.04847, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04847
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.18it/s]


evaluating ...
epoch 25, weight=0.50000, train-loss=0.05104, optimal-val-loss=nan, val-loss=0.04881, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04881
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.13it/s]


evaluating ...
epoch 26, weight=0.50000, train-loss=0.05243, optimal-val-loss=nan, val-loss=0.04826, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04826
save model ...
saved!
save new best model: last-best-loss: 0.04844, new-best-loss: 0.04826, epoch: 26
saved!
----------------------------------------------------------------------------------------------------


80it [00:20,  3.89it/s]


evaluating ...
epoch 27, weight=0.50000, train-loss=0.05269, optimal-val-loss=nan, val-loss=0.04858, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04858
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:20,  3.89it/s]


evaluating ...
epoch 28, weight=0.50000, train-loss=0.05063, optimal-val-loss=nan, val-loss=0.04827, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04827
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.02it/s]


evaluating ...
epoch 29, weight=0.50000, train-loss=0.05143, optimal-val-loss=nan, val-loss=0.04857, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04857
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.14it/s]


evaluating ...
epoch 30, weight=0.50000, train-loss=0.05117, optimal-val-loss=nan, val-loss=0.04823, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04823
save model ...
saved!
save new best model: last-best-loss: 0.04826, new-best-loss: 0.04823, epoch: 30


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


saved!
----------------------------------------------------------------------------------------------------


80it [00:20,  3.92it/s]


evaluating ...
epoch 31, weight=0.50000, train-loss=0.05058, optimal-val-loss=nan, val-loss=0.04836, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04836
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.11it/s]


evaluating ...
epoch 32, weight=0.50000, train-loss=0.05100, optimal-val-loss=nan, val-loss=0.04830, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04830
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.15it/s]


evaluating ...
epoch 33, weight=0.50000, train-loss=0.05324, optimal-val-loss=nan, val-loss=0.04823, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04823
save model ...
saved!
save new best model: last-best-loss: 0.04823, new-best-loss: 0.04823, epoch: 33
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.09it/s]


evaluating ...
epoch 34, weight=0.50000, train-loss=0.05144, optimal-val-loss=nan, val-loss=0.04840, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04840
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.09it/s]


evaluating ...
epoch 35, weight=0.50000, train-loss=0.05053, optimal-val-loss=nan, val-loss=0.04818, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04818
save model ...
saved!
save new best model: last-best-loss: 0.04823, new-best-loss: 0.04818, epoch: 35
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.36it/s]


evaluating ...
epoch 36, weight=0.50000, train-loss=0.04890, optimal-val-loss=nan, val-loss=0.04839, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04839
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.33it/s]


evaluating ...
epoch 37, weight=0.50000, train-loss=0.04912, optimal-val-loss=nan, val-loss=0.04825, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04825
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.41it/s]


evaluating ...
epoch 38, weight=0.50000, train-loss=0.05131, optimal-val-loss=nan, val-loss=0.04799, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04799
save model ...
saved!
save new best model: last-best-loss: 0.04818, new-best-loss: 0.04799, epoch: 38
saved!
----------------------------------------------------------------------------------------------------


80it [00:26,  3.03it/s]


evaluating ...
epoch 39, weight=0.50000, train-loss=0.05181, optimal-val-loss=nan, val-loss=0.04841, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04841
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.34it/s]


evaluating ...
epoch 40, weight=0.50000, train-loss=0.05197, optimal-val-loss=nan, val-loss=0.04847, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04847
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.28it/s]


evaluating ...
epoch 41, weight=0.50000, train-loss=0.04978, optimal-val-loss=nan, val-loss=0.04790, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04790
save model ...
saved!
save new best model: last-best-loss: 0.04799, new-best-loss: 0.04790, epoch: 41
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.04it/s]


evaluating ...
epoch 42, weight=0.50000, train-loss=0.05080, optimal-val-loss=nan, val-loss=0.04846, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04846
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.41it/s]


evaluating ...
epoch 43, weight=0.50000, train-loss=0.05039, optimal-val-loss=nan, val-loss=0.04804, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04804
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.13it/s]


evaluating ...
epoch 44, weight=0.50000, train-loss=0.04973, optimal-val-loss=nan, val-loss=0.04809, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04809
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:21,  3.79it/s]


evaluating ...
epoch 45, weight=0.50000, train-loss=0.05081, optimal-val-loss=nan, val-loss=0.04827, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04827
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:18,  4.23it/s]


evaluating ...
epoch 46, weight=0.50000, train-loss=0.04845, optimal-val-loss=nan, val-loss=0.04800, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04800
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:22,  3.63it/s]


evaluating ...
epoch 47, weight=0.50000, train-loss=0.05073, optimal-val-loss=nan, val-loss=0.04801, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04801
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.09it/s]


evaluating ...
epoch 48, weight=0.50000, train-loss=0.04987, optimal-val-loss=nan, val-loss=0.04806, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04806
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:19,  4.00it/s]


evaluating ...
epoch 49, weight=0.50000, train-loss=0.05041, optimal-val-loss=nan, val-loss=0.04820, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04820
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:22,  3.56it/s]


evaluating ...
epoch 50, weight=0.50000, train-loss=0.04888, optimal-val-loss=nan, val-loss=0.04800, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04800
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:21,  3.79it/s]


evaluating ...
epoch 51, weight=0.50000, train-loss=0.04903, optimal-val-loss=nan, val-loss=0.04809, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04809
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:24,  3.29it/s]


evaluating ...
epoch 52, weight=0.50000, train-loss=0.04868, optimal-val-loss=nan, val-loss=0.04788, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04788
save model ...
saved!
save new best model: last-best-loss: 0.04790, new-best-loss: 0.04788, epoch: 52
saved!
----------------------------------------------------------------------------------------------------


80it [00:24,  3.33it/s]


evaluating ...
epoch 53, weight=0.50000, train-loss=0.04911, optimal-val-loss=nan, val-loss=0.04821, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04821
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:26,  3.05it/s]


evaluating ...
epoch 54, weight=0.50000, train-loss=0.04894, optimal-val-loss=nan, val-loss=0.04788, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04788
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:27,  2.94it/s]


evaluating ...
epoch 55, weight=0.50000, train-loss=0.04778, optimal-val-loss=nan, val-loss=0.04802, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04802
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:28,  2.82it/s]


evaluating ...
epoch 56, weight=0.50000, train-loss=0.04864, optimal-val-loss=nan, val-loss=0.04807, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04807
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:29,  2.74it/s]


evaluating ...
epoch 57, weight=0.50000, train-loss=0.04813, optimal-val-loss=nan, val-loss=0.04780, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04780
save model ...
saved!
save new best model: last-best-loss: 0.04788, new-best-loss: 0.04780, epoch: 57
saved!
----------------------------------------------------------------------------------------------------


80it [00:34,  2.32it/s]


evaluating ...
epoch 58, weight=0.50000, train-loss=0.04832, optimal-val-loss=nan, val-loss=0.04785, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04785
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:33,  2.40it/s]


evaluating ...
epoch 59, weight=0.50000, train-loss=0.04719, optimal-val-loss=nan, val-loss=0.04792, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04792
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:33,  2.38it/s]


evaluating ...
epoch 60, weight=0.50000, train-loss=0.04726, optimal-val-loss=nan, val-loss=0.04797, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04797
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:35,  2.24it/s]


evaluating ...
epoch 61, weight=0.50000, train-loss=0.04825, optimal-val-loss=nan, val-loss=0.04796, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04796
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:33,  2.40it/s]


evaluating ...
epoch 62, weight=0.50000, train-loss=0.04930, optimal-val-loss=nan, val-loss=0.04788, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04788
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:37,  2.16it/s]


evaluating ...
epoch 63, weight=0.50000, train-loss=0.04744, optimal-val-loss=nan, val-loss=0.04791, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04791
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:39,  2.04it/s]


evaluating ...
epoch 64, weight=0.50000, train-loss=0.04752, optimal-val-loss=nan, val-loss=0.04793, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04793
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:38,  2.08it/s]


evaluating ...
epoch 65, weight=0.50000, train-loss=0.04814, optimal-val-loss=nan, val-loss=0.04776, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04776
save model ...
saved!
save new best model: last-best-loss: 0.04780, new-best-loss: 0.04776, epoch: 65
saved!
----------------------------------------------------------------------------------------------------


80it [00:59,  1.34it/s]


evaluating ...
epoch 66, weight=0.50000, train-loss=0.04765, optimal-val-loss=nan, val-loss=0.04787, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04787
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:40,  1.98it/s]


evaluating ...
epoch 67, weight=0.50000, train-loss=0.04842, optimal-val-loss=nan, val-loss=0.04790, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04790
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:44,  1.80it/s]


evaluating ...
epoch 68, weight=0.50000, train-loss=0.04752, optimal-val-loss=nan, val-loss=0.04777, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04777
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:47,  1.70it/s]


evaluating ...
epoch 69, weight=0.50000, train-loss=0.04842, optimal-val-loss=nan, val-loss=0.04779, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04779
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:48,  1.65it/s]


evaluating ...
epoch 70, weight=0.50000, train-loss=0.04869, optimal-val-loss=nan, val-loss=0.04776, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04776
save model ...
saved!
save new best model: last-best-loss: 0.04776, new-best-loss: 0.04776, epoch: 70
saved!
----------------------------------------------------------------------------------------------------


80it [00:52,  1.53it/s]


evaluating ...
epoch 71, weight=0.50000, train-loss=0.04550, optimal-val-loss=nan, val-loss=0.04785, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04785
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:48,  1.64it/s]


evaluating ...
epoch 72, weight=0.50000, train-loss=0.04914, optimal-val-loss=nan, val-loss=0.04773, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04773
save model ...
saved!
save new best model: last-best-loss: 0.04776, new-best-loss: 0.04773, epoch: 72
saved!
----------------------------------------------------------------------------------------------------


80it [00:50,  1.57it/s]


evaluating ...
epoch 73, weight=0.50000, train-loss=0.04998, optimal-val-loss=nan, val-loss=0.04778, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04778
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:51,  1.56it/s]


evaluating ...
epoch 74, weight=0.50000, train-loss=0.04701, optimal-val-loss=nan, val-loss=0.04779, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04779
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:52,  1.53it/s]


evaluating ...
epoch 75, weight=0.50000, train-loss=0.04744, optimal-val-loss=nan, val-loss=0.04773, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04773
save model ...
saved!
save new best model: last-best-loss: 0.04773, new-best-loss: 0.04773, epoch: 75
saved!
----------------------------------------------------------------------------------------------------


80it [00:51,  1.55it/s]


evaluating ...
epoch 76, weight=0.50000, train-loss=0.04747, optimal-val-loss=nan, val-loss=0.04776, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04776
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:52,  1.52it/s]


evaluating ...
epoch 77, weight=0.50000, train-loss=0.04805, optimal-val-loss=nan, val-loss=0.04777, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04777
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:52,  1.53it/s]


evaluating ...
epoch 78, weight=0.50000, train-loss=0.04727, optimal-val-loss=nan, val-loss=0.04776, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04776
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:57,  1.39it/s]


evaluating ...
epoch 79, weight=0.50000, train-loss=0.04799, optimal-val-loss=nan, val-loss=0.04774, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04774
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:54,  1.48it/s]


evaluating ...
epoch 80, weight=0.50000, train-loss=0.04751, optimal-val-loss=nan, val-loss=0.04775, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04775
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:59,  1.34it/s]


evaluating ...
epoch 81, weight=0.50000, train-loss=0.04653, optimal-val-loss=nan, val-loss=0.04773, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04773
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [01:05,  1.21it/s]


evaluating ...
epoch 82, weight=0.50000, train-loss=0.04882, optimal-val-loss=nan, val-loss=0.04769, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04769
save model ...
saved!
save new best model: last-best-loss: 0.04773, new-best-loss: 0.04769, epoch: 82
saved!
----------------------------------------------------------------------------------------------------


80it [00:56,  1.42it/s]


evaluating ...
epoch 83, weight=0.50000, train-loss=0.04713, optimal-val-loss=nan, val-loss=0.04772, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04772
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:51,  1.56it/s]


evaluating ...
epoch 84, weight=0.50000, train-loss=0.04766, optimal-val-loss=nan, val-loss=0.04766, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04766
save model ...
saved!
save new best model: last-best-loss: 0.04769, new-best-loss: 0.04766, epoch: 84
saved!
----------------------------------------------------------------------------------------------------


80it [00:47,  1.69it/s]


evaluating ...
epoch 85, weight=0.50000, train-loss=0.04714, optimal-val-loss=nan, val-loss=0.04771, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04771
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:45,  1.78it/s]


evaluating ...
epoch 86, weight=0.50000, train-loss=0.04836, optimal-val-loss=nan, val-loss=0.04771, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04771
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:43,  1.84it/s]


evaluating ...
epoch 87, weight=0.50000, train-loss=0.04764, optimal-val-loss=nan, val-loss=0.04763, 
plotting ...


C:\Users\gg868\thesis\NJODE\train.py:998: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_metric = pd.concat([df_metric, df_m_app], ignore_index=True)


optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04763
save model ...
saved!
save new best model: last-best-loss: 0.04766, new-best-loss: 0.04763, epoch: 87
saved!
----------------------------------------------------------------------------------------------------


80it [00:41,  1.94it/s]


evaluating ...
epoch 88, weight=0.50000, train-loss=0.04677, optimal-val-loss=nan, val-loss=0.04766, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04766
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:39,  2.00it/s]


evaluating ...
epoch 89, weight=0.50000, train-loss=0.04786, optimal-val-loss=nan, val-loss=0.04773, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04773
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:38,  2.09it/s]


evaluating ...
epoch 90, weight=0.50000, train-loss=0.04721, optimal-val-loss=nan, val-loss=0.04768, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04768
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:36,  2.17it/s]


evaluating ...
epoch 91, weight=0.50000, train-loss=0.04741, optimal-val-loss=nan, val-loss=0.04770, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04770
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:37,  2.15it/s]


evaluating ...
epoch 92, weight=0.50000, train-loss=0.04709, optimal-val-loss=nan, val-loss=0.04768, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04768
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:32,  2.45it/s]


evaluating ...
epoch 93, weight=0.50000, train-loss=0.04759, optimal-val-loss=nan, val-loss=0.04768, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04768
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:32,  2.49it/s]


evaluating ...
epoch 94, weight=0.50000, train-loss=0.04607, optimal-val-loss=nan, val-loss=0.04792, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04792
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:29,  2.75it/s]


evaluating ...
epoch 95, weight=0.50000, train-loss=0.04820, optimal-val-loss=nan, val-loss=0.04768, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04768
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:30,  2.64it/s]


evaluating ...
epoch 96, weight=0.50000, train-loss=0.04945, optimal-val-loss=nan, val-loss=0.04765, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04765
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:29,  2.70it/s]


evaluating ...
epoch 97, weight=0.50000, train-loss=0.04798, optimal-val-loss=nan, val-loss=0.04766, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04766
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:30,  2.65it/s]


evaluating ...
epoch 98, weight=0.50000, train-loss=0.04798, optimal-val-loss=nan, val-loss=0.04769, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04769
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:29,  2.74it/s]


evaluating ...
epoch 99, weight=0.50000, train-loss=0.04615, optimal-val-loss=nan, val-loss=0.04774, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04774
save model ...
saved!
----------------------------------------------------------------------------------------------------


80it [00:29,  2.69it/s]


evaluating ...
epoch 100, weight=0.50000, train-loss=0.04831, optimal-val-loss=nan, val-loss=0.04772, 
plotting ...
optimal test-loss (with current weight=0.50000): 0.00000
model test-loss (with current weight=0.50000): 0.04772
save model ...
saved!
----------------------------------------------------------------------------------------------------


0

In [25]:
params_dict = {
    'input_size': 9,
    'hidden_size': 10,
    'output_size': 9,
    'ode_nn': ((50, "tanh"), (50, "tanh")),
    'readout_nn': ((50, "tanh"), (50, "tanh")),
    'enc_nn': ((50, "tanh"), (50, "tanh")),
    'use_rnn': False,
    'options': {'which_loss': 'easy'},
    "input_coords": np.arange(9),
    "output_coords": np.arange(9),
    "signature_coords": np.arange(9)
}
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
from models import get_ckpt_model, NJODE
model = NJODE(**params_dict).to(device)
optimizer = torch.optim.Adam(model.parameters())
get_ckpt_model("../data/saved_models/id-87/best_checkpoint/", model, optimizer, device)
model.eval()

using loss: easy
neuralODE use input scaling with tanh
use residual network: input_size=9, output_size=10
use residual network: input_size=10, output_size=9


NJODE(
  (ode_f): ODEFunc(
    (f): Sequential(
      (0): Linear(in_features=21, out_features=50, bias=True)
      (1): Tanh()
      (2): Dropout(p=0, inplace=False)
      (3): Linear(in_features=50, out_features=50, bias=True)
      (4): Tanh()
      (5): Dropout(p=0, inplace=False)
      (6): Linear(in_features=50, out_features=10, bias=True)
    )
  )
  (encoder_map): FFNN(
    (ffnn): Sequential(
      (0): Linear(in_features=9, out_features=50, bias=True)
      (1): Tanh()
      (2): Dropout(p=0, inplace=False)
      (3): Linear(in_features=50, out_features=50, bias=True)
      (4): Tanh()
      (5): Dropout(p=0, inplace=False)
      (6): Linear(in_features=50, out_features=10, bias=True)
    )
  )
  (readout_map): FFNN(
    (ffnn): Sequential(
      (0): Linear(in_features=10, out_features=50, bias=True)
      (1): Tanh()
      (2): Dropout(p=0, inplace=False)
      (3): Linear(in_features=50, out_features=50, bias=True)
      (4): Tanh()
      (5): Dropout(p=0, inplace=False)
 

In [26]:
data_1k=np.load("../data/training_data/OrnsteinUhlenbeckWithCrossTerms-92/data.npy")

In [36]:
data_1k.shape

(1000, 9, 101)

In [39]:
data_1k[0,:,0]

array([1.  , 1.5 , 2.  , 1.  , 2.25, 4.  , 1.5 , 2.  , 3.  ])

In [40]:
start_X = torch.tensor(np.array([1.0, 1.5, 2.0, 1.0, 2.25, 4.0, 1.5, 2.0, 3.0]), dtype=torch.float).unsqueeze(0)

In [41]:
start_X.shape

torch.Size([1, 9])

In [16]:
def vector_to_symmetric_matrix(X):
    """
    Converts input vector X of shape (batch_size, dim*2 + dim*(dim - 1)//2)
    to a symmetric matrix of shape (batch_size, dim, dim).
    """
    batch_size, total_dim = X.shape

    # Solve quadratic equation: dim^2 + dim = 2 * total_dim
    # to find dim
    a = 1
    b = 1
    c = -2 * total_dim
    discriminant = b**2 - 4*a*c
    dim = int((-b + discriminant**0.5) / (2 * a))

    assert dim * 2 + dim * (dim - 1) // 2 == total_dim, "Invalid input dimensions"

    # Extract parts
    squared_terms = X[:, dim:2*dim]  # shape: (batch_size, dim)
    cross_terms = X[:, 2*dim:]       # shape: (batch_size, dim*(dim - 1)//2)

    symm_matrix = torch.zeros(batch_size, dim, dim, dtype=X.dtype, device=X.device)

    # Fill diagonal
    for i in range(dim):
        symm_matrix[:, i, i] = squared_terms[:, i]

    # Fill off-diagonal with cross terms
    idx = 0
    for i in range(dim):
        for j in range(i+1, dim):
            symm_matrix[:, i, j] = cross_terms[:, idx]
            symm_matrix[:, j, i] = cross_terms[:, idx]
            idx += 1

    return symm_matrix


In [27]:
 def generate_next_value( X_t, mu_t, sigma_t, delta_t):
    """
    Generate the next value in the time series using the Euler-Maruyama scheme.

    :param X_t: current value tensor of shape (batch_size, d)
    :param mu_t: drift coefficient tensor of shape (batch_size, d)
    :param sigma_t: diffusion coefficient tensor of shape ( d, d)
    :param delta_t: time difference float
    :return: next value tensor of shape (batch_size, d)
    """

    delta_Wt = torch.randn_like(X_t) * np.sqrt(delta_t)
    delta_Wt_sigma_t = torch.bmm(delta_Wt.unsqueeze(1), sigma_t).squeeze(1)
    X_t_next = X_t + mu_t * delta_t + delta_Wt_sigma_t

    return X_t_next

In [28]:
def expand_features(X):
    """
    Input:
        X: Tensor of shape (batch_size, dim)
    Output:
        Y: Tensor of shape (batch_size, dim + dim + dim*(dim - 1)//2)
           = (batch_size, dim*2 + dim*(dim - 1)//2)
    """
    batch_size, dim = X.shape

    squares = X ** 2  # shape: (batch_size, dim)

    # Compute pairwise products (only upper triangle without diagonal)
    products = []
    for i in range(dim):
        for j in range(i + 1, dim):
            products.append(X[:, i] * X[:, j])  # shape: (batch_size,)

    products = torch.stack(products, dim=1) if products else torch.empty(batch_size, 0, device=X.device)

    # Concatenate all parts
    Y = torch.cat([X, squares, products], dim=1)

    return Y


In [84]:
expand_features(start_X[:,:3])

tensor([[1.0000, 1.5000, 2.0000, 1.0000, 2.2500, 4.0000, 1.5000, 2.0000, 3.0000]])

In [29]:
dim=3
times=np.array([])
time_ptr = np.array([0])
obs_idx = torch.tensor([],dtype=torch.long)
delta_t=0.01
X= torch.tensor([], dtype=torch.float)
start_X = torch.tensor(np.array([1.0, 1.5, 2.0, 1.0, 2.25, 4.0, 1.5, 2.0, 3.0]), dtype=torch.float).unsqueeze(0)
n_obs_ot=torch.tensor([0], dtype=torch.float)

for i in range(1,101):
    T=0.01*i
    pred=model.get_pred(times, time_ptr, X, obs_idx, delta_t, T, start_X, n_obs_ot)["pred"][-1] 
    print(pred)
    if i==1:
        X_t = start_X 
    else: 
        X_t = X_next  
    mu_hat_t = (pred[:,:dim]-X_t[:,:dim])/delta_t 
    print(mu_hat_t)
    term_1= (vector_to_symmetric_matrix(pred) - vector_to_symmetric_matrix(start_X))/delta_t 
    term_2 = X_t[:,:dim].T@mu_hat_t+mu_hat_t.T@X_t[:,:dim]
    sig_hat_t = term_1-term_2
    print(sig_hat_t)
    print(np.linalg.eigvals(sig_hat_t.detach().numpy()))
    sigma_hat_t = np.linalg.cholesky(make_positive_definite(sig_hat_t.detach().numpy()))
    print(np.linalg.eigvals(sigma_hat_t))
    X_next_points = generate_next_value( X_t[:,:dim], mu_hat_t, torch.from_numpy(sigma_hat_t).to(torch.float), delta_t)
    X_next = expand_features(X_next_points)
    X= torch.cat((X,X_next), dim=0)
    times=np.append(times, delta_t*i)
    time_ptr = np.append(time_ptr, i)
    obs_idx=torch.cat((obs_idx, torch.tensor([0], dtype=torch.long)))
    n_obs_ot+=1

tensor([[1.0002, 1.4997, 1.9997, 1.0004, 2.2492, 3.9987, 1.4999, 2.0003, 2.9990]],
       grad_fn=<SelectBackward0>)
tensor([[ 0.0205, -0.0347, -0.0345]], grad_fn=<DivBackward0>)
tensor([[[ 0.0002, -0.0038,  0.0224],
         [-0.0038,  0.0235,  0.0171],
         [ 0.0224,  0.0171,  0.0088]]], grad_fn=<SubBackward0>)
[[-0.0226716   0.01728697  0.03791685]]
[[0.00152589 0.21351068 0.15108797]]
tensor([[0.9876, 1.5127, 1.9993, 0.9754, 2.2885, 3.9973, 1.4939, 1.9747, 3.0245]],
       grad_fn=<SelectBackward0>)
tensor([[ 0.0203, -0.0358, -0.0343]], grad_fn=<DivBackward0>)
tensor([[[-2.5041, -0.6056, -2.5337],
         [-0.6056,  3.9580,  2.5756],
         [-2.5337,  2.5756, -0.1330]]], grad_fn=<SubBackward0>)
[[-4.223031   -0.02017581  5.564077  ]]
[[1.87609384e-03 2.82269409e+00 1.31107389e+00]]
tensor([[0.9777, 1.5416, 1.9990, 0.9560, 2.3769, 3.9962, 1.5073, 1.9547, 3.0820]],
       grad_fn=<SelectBackward0>)
tensor([[ 0.0202, -0.0371, -0.0339]], grad_fn=<DivBackward0>)
tensor([[[-4.4416

LinAlgError: Matrix is not positive definite